In [9]:
import os, sys
sys.path.append("/home/e78368jw/Documents/MULE/")

import numpy as np
import h5py
import pandas as pd

from packs.types import types
from packs.core.io import reader
from packs.core.io import writer
from packs.types.types import rwf_type_WD1

In [19]:
#def read_evt(file_group):
    
def read_lazy():
    
    with h5py.File('/home/casper/Documents/MULE/packs/tests/data/three_channels_WD2.h5') as f:
        gr = f['rwf']
        rwf_0  = gr['rwf_-1']
    
        print(gr)
        print(rwf_0)
    
        for row in rwf_0:
            yield row

In [20]:
x = read_lazy()

In [21]:
q = next(x)
print(q)

<HDF5 group "/rwf" (1 members)>
<HDF5 dataset "rwf_-1": shape (246,), type "|V4008">
(0, 0, [ 0.   , -0.384,  0.192, -0.384, -0.256, -0.512, -0.064, -0.32 ,  0.064, -0.128,  0.128,  0.512,  0.128, -0.064,  0.128,  0.   ,  0.192, -0.192,  0.   , -0.32 ,  0.256, -0.32 ,  0.256, -0.064,  0.   ,  0.192, -0.128, -0.128,  0.192, -0.128,  0.512,  0.32 ,  0.256,  0.   ,  0.32 , -0.128,  0.192, -0.128,  0.192, -0.128, -0.064, -0.064,  0.   , -0.448, -0.192, -0.128,  0.256, -0.32 ,  0.   , -0.576, -0.256, -0.256,  0.32 , -0.128,  0.   ,  0.064,  0.384, -0.192, -0.064,  0.064,  0.512,  0.192,  0.256,  0.32 ,  0.32 , -0.064,  0.32 , -0.128, -0.064, -0.512, -0.192, -0.256,  0.   , -0.32 , -0.256, -0.384, -0.128, -0.064,  0.   ,  0.   ,  0.128, -0.128,  0.256, -0.064, -0.064, -0.192,  0.512, -0.064,  0.256,  0.32 ,  0.128,  0.   ,  0.192,  0.   , -0.128, -0.576, -0.192, -0.384,  0.   ,  0.   ,  0.128, -0.128,  0.64 , -0.064,  0.256,  0.192,  0.128, -0.512, -0.512, -0.704,  0.   , -0.128,  0.32 ,  0.192,  0.192, -0.064,  0.256, -0.256,  0.256, -0.064,  0.192, -0.256,  0.064, -0.32 , -0.064, -0.576, -0.064, -0.192,  0.256, -0.32 , -0.064, -0.128,  0.256, -0.32 ,  0.192,  0.192,  0.512,  0.32 ,  0.256, -0.192,  0.   , -0.064,  0.128, -0.512,  0.   ,  0.064,  0.32 , -0.32 ,  0.064,  0.192,  0.256, -0.32 ,  0.   ,  0.064,  0.256, -0.128,  0.   , -0.064,  0.   , -0.064, -0.384, -0.32 ,  0.128,  0.192,  0.   ,  0.   ,  0.128,  0.192,  0.256, -0.064,  0.256,  0.32 ,  0.128,  0.32 ,  0.768,  0.384,  0.448,  0.32 ,  0.576,  0.512,  0.512,  0.128,  0.192, -0.128,  0.256, -0.064,  0.384, -0.192,  0.064, -0.32 ,  0.256,  0.32 ,  0.256,  0.32 ,  0.32 ,  0.32 ,  0.32 ,  0.192,  0.512,  0.128,  0.192,  0.32 ,  0.32 , -0.128,  0.32 ,  0.192, -0.064,  0.128,  0.256, -0.128,  0.128, -0.32 , -0.128, -0.64 , -0.064,  0.   ,  0.32 ,  0.384,  0.256,  0.384,  0.32 ,  0.   ,  0.128, -0.064,  0.064, -0.128,  0.256, -0.32 ,  0.384, -0.256,  0.192, -0.256,  0.   , -0.128,  0.064, -0.256,  0.256, -0.128,  0.   , -0.256, -0.064, -0.448, -0.192, -0.32 , -0.192, -0.256,  0.256,  0.32 ,  0.512,  0.192,  0.256,  0.32 ,  0.32 , -0.128,  0.128,  0.   ,  0.32 ,  0.32 ,  0.256, -0.064,  0.256, -0.256,  0.256, -0.064,  0.32 , -0.192,  0.192, -0.256,  0.256, -0.064,  0.512,  0.192,  0.   , -0.064,  0.128, -0.192,  0.384,  0.   ,  0.384, -0.064,  0.704,  0.   ,  0.256, -0.192, -0.192, -0.128,  0.192, -0.064,  0.32 , -0.064, -0.064,  0.   , -0.192, -0.448,  0.256, -0.256,  0.32 ,  0.192,  0.32 ,  0.256,  0.128, -0.128,  0.192, -0.128,  0.256,  0.128,  0.512,  0.704,  0.192,  0.192,  0.448, -0.192,  0.192, -0.128,  0.32 , -0.128,  0.   , -0.064,  0.192,  0.   , -0.256,  0.064,  0.192, -0.128, -0.064,  0.   ,  0.512,  0.32 ,  0.   , -0.32 ,  0.32 ,  0.192,  0.256, -0.384,  0.32 , -0.064,  0.512,  0.   ,  0.   ,  0.128,  0.128, -0.384,  0.128, -0.32 ,  0.128,  0.192,  0.32 ,  0.384,  0.576,  0.192,  0.064,  0.192,  0.512,  0.32 ,  0.192,  0.064,  0.   ,  0.   , -0.064, -0.32 ,  0.   ,  0.128,  0.448,  0.32 ,  0.192, -0.064,  0.32 ,  0.128,  0.128, -0.256,  0.32 ,  0.448,  0.32 ,  0.32 , -0.128, -0.448,  0.   , -0.128,  0.128, -0.128,  0.   ,  0.128,  0.512,  0.064,  0.256,  0.   ,  0.192, -0.128,  0.128,  0.192,  0.   , -0.576,  0.064, -0.128,  0.256, -0.192, -0.128, -0.512, -0.128,  0.   ,  0.256,  0.128,  0.192,  0.32 ,  0.   ,  0.32 ,  0.512,  0.192,  0.32 ,  0.448,  0.32 ,  0.064,  0.32 ,  0.32 ,  0.256,  0.64 ,  0.576,  0.192,  0.192,  0.192,  0.384,  0.32 ,  0.128, -0.32 , -0.064, -0.128,  0.512,  0.384,  0.448,  0.32 ,  0.256, -0.064, -0.064, -0.192,  0.   ,  0.256,  0.32 , -0.256,  0.256,  0.   ,  0.256, -0.448, -0.192, -0.064,  0.512, -0.064,  0.256, -0.064,  0.128, -0.128,  0.   , -0.256,  0.   , -0.192,  0.256,  0.   ,  0.256, -0.064,  0.512,  0.192,  0.448,  0.128, -0.064, -0.32 ,  0.256, -0.064,  0.064, -0.064,  0.32 ,  0.192,  0.32 ,  0.128,  0.192,  0.192, -0.064, -0.448,  0.256, -0.448,  0.256,  0.192,  0.384, -0.064,  0.   , -0.064,  0.064,  0.128,  0.32 , -0.064,  0.   ,  0.128,  0.256, -0.192,  0.128, -0.576, -0.256, -0.32 ,  0.128, -0.128,  0.192,  0.32 , -0.064, -0.128,  0.192, -0.064,  0.128, -0.448, -0.064, -0.256,  0.   ,  0.128,  0.128, -0.192,  0.   , -0.128, -0.064, -0.448, -0.192, -0.128,  0.256,  0.064,  0.128, -0.064,  0.192,  0.064, -0.256, -0.384,  0.064, -0.192, -0.128, -0.128,  0.128,  0.192,  0.128, -0.32 ,  0.   , -0.128,  0.064,  0.128,  0.32 , -0.64 , -0.192,  0.192,  0.576,  0.064,  0.   , -0.64 ,  0.064, -0.128, -0.128, -0.32 ,  0.   , -0.064,  0.256,  0.192,  0.128,  0.   ,  0.384, -0.128,  0.   , -0.32 ,  0.128, -0.064,  0.128,  0.   ,  0.448, -0.064,  0.128,  0.192,  0.384,  0.384,  0.32 ,  0.192,  0.256, -0.128,  0.32 , -0.192,  0.128, -0.192,  0.256, -0.384,  0.   , -0.064,  0.384, -0.32 , -0.192, -0.32 ,  0.064, -0.128,  0.   , -0.128,  0.128,  0.064,  0.128,  0.   ,  0.256, -0.128,  0.128,  0.32 ,  0.384, -0.32 ,  0.   , -0.448,  0.256, -0.384,  0.   ,  0.32 ,  0.448,  0.448,  0.704,  0.448,  0.32 , -0.128,  0.128, -0.32 ,  0.192, -0.256,  0.192,  0.384,  0.32 ,  0.   ,  0.064,  0.448,  0.32 ,  0.384,  0.128, -0.064,  0.32 , -0.128, -0.192,  0.384,  0.256,  0.384,  0.96 ,  0.64 ,  0.768,  0.64 ,  0.128, -0.832, -3.008, -4.416, -3.904, -3.2  , -1.536,  0.384,  3.392,  5.312,  5.888,  4.672,  2.56 ,  0.96 , -0.128, -1.344, -1.408, -1.792, -1.472, -2.048, -1.28 , -0.32 ,  1.152,  0.96 ,  0.512, -0.448, -0.64 , -1.344, -0.896, -0.192,  1.152,  1.536,  2.304,  1.728,  1.536,  0.704, -0.384, -0.832, -0.64 , -1.088, -1.28 , -1.216, -0.448, -0.32 ,  0.256,  0.96 ,  1.536,  1.408,  1.152,  1.216,  0.768,  0.128, -0.192, -1.088, -0.768, -1.536, -1.024, -0.832, -0.064,  0.256,  0.96 ,  0.896,  1.28 ,  0.576,  0.384,  0.192,  0.128, -0.512, -0.256, -0.32 , -0.256, -0.064,  0.448,  0.704,  0.704,  0.32 ,  0.192,  0.192,  0.064, -0.32 , -0.384, -0.768, -0.064,  0.128,  0.256,  0.576,  0.512,  0.192,  0.384,  0.256,  0.384, -0.192,  0.   , -0.256,  0.128, -0.448,  0.128, -0.192,  0.384,  0.   ,  0.256,  0.32 ,  0.704,  0.192,  0.256, -0.192,  0.   , -0.576,  0.064, -0.192,  0.32 ,  0.384,  0.256,  0.576,  0.768,  0.384,  0.448,  0.32 ,  0.384, -0.064,  0.   ,  0.192, -0.064, -0.32 , -0.064,  0.192,  0.32 ,  0.064,  0.   ,  0.   ,  0.448, -0.064,  0.   , -0.128,  0.256, -0.128,  0.256, -0.128,  0.192,  0.   ,  0.128, -0.256,  0.128,  0.192,  0.256, -0.128,  0.256,  0.256,  0.32 , -0.192,  0.128,  0.   ,  0.256,  0.128,  0.448,  0.256,  0.448,  0.32 ,  0.256, -0.32 ,  0.256,  0.192,  0.192, -0.32 ,  0.32 ,  0.064,  0.256, -0.064,  0.384,  0.384,  0.192, -0.384, -0.256, -0.256,  0.384,  0.384,  0.512,  0.384,  0.192,  0.192,  0.384,  0.384,  0.448,  0.576,  0.32 ,  0.384,  0.32 ,  0.192,  0.   ,  0.128,  0.32 ,  0.384,  0.448,  0.384,  0.576,  0.   ,  0.192,  0.192,  0.32 ,  0.064,  0.064, -0.064,  0.32 ,  0.32 ,  0.256,  0.   ,  0.32 , -0.064,  0.128, -0.128,  0.   , -0.064,  0.256,  0.192,  0.256,  0.384,  0.768,  0.32 ,  0.448,  0.064,  0.   ,  0.256,  0.448,  0.32 ,  0.256,  0.192,  0.448,  0.832,  0.448,  0.32 ,  0.064, -0.192,  0.512,  0.256,  0.384,  0.192,  0.32 ,  0.128,  0.384,  0.32 , -0.064, -0.256,  0.256, -0.256,  0.256,  0.192,  0.384, -0.064,  0.384,  0.192,  0.256,  0.256,  0.64 ,  0.512,  0.   , -0.448,  0.   , -0.704, -1.024, -1.536, -0.704,  0.704,  1.92 ,  1.92 ,  1.856,  2.304,  3.52 ,  4.096,  3.392,  1.728, -0.256, -2.688, -3.584, -3.456, -2.24 , -1.792, -2.752, -3.392, -2.176, -0.192,  2.368,  2.816,  2.88 ,  2.368,  1.28 ,  0.384,  1.216,  1.344,  1.664,  1.472,  0.64 , -0.064, -1.088, -1.792, -1.536, -1.6  , -0.96 , -1.344, -0.96 , -0.384,  0.768,  1.6  ,  2.304,  2.432,  2.048,  1.152,  0.192, -0.768, -1.024, -1.344, -1.088, -1.344, -0.768, -0.512,  0.192,  0.576,  1.216,  1.792,  1.408,  0.704,  0.32 , -0.256, -0.128, -0.832, -0.512, -0.832, -0.512, -0.32 ,  0.384,  0.704,  1.536,  1.856,  1.472,  1.088,  1.28 ,  0.448,  0.256, -0.832, -0.448, -1.28 , -1.28 , -1.216, -0.64 , -0.128,  0.768,  1.344,  1.344,  1.216,  0.64 ,  0.32 ,  0.768,  0.512,  0.384,  0.32 ,  0.256, -0.576,  0.   , -0.448,  0.256, -0.192,  0.   , -0.256,  0.   , -0.064])

In [25]:
display(pd.DataFrame(map(list, [next(x)]), columns = (types.rwf_type(1000)).names))

   event_number  channels                                                rwf
0             1         1  [-0.064, -0.448, -0.384, -0.704, -0.576, -0.12...

In [ ]:
event_info_type = np.dtype([
            ('event_number', np.uint32),
            ('timestamp', np.uint64),
            ('samples', np.uint32),
            ('sampling_period', np.uint64),
            ('channels', np.int32),
            ])

In [2]:
test_dtype = np.dtype(
                [('int', np.uint32),
                ('float', np.float32),
                ('bool', bool),
                ('bigfloat', np.float64),
                 ])

test_dataset = np.array((0, 1.0, False, 25.23), dtype = test_dtype)
test_dataset_2 = np.array((5, 4.0, True, 99.99), dtype = test_dtype)

In [3]:
test_dataset

array((0, 1., False, 25.23),
      dtype=[('int', '<u4'), ('float', '<f4'), ('bool', '?'), ('bigfloat', '<f8')])

In [8]:
with writer('test_file.h5', 'test_group', overwrite = True) as scribe:
    scribe('test_dataset', test_dataset)
    scribe('test_dataset', test_dataset_2)
    scribe('test_dataset', test_dataset)
    scribe('test_dataset', test_dataset_2)
    scribe('test_dataset', test_dataset)
    scribe('test_dataset', test_dataset_2)
    scribe('test_dataset', test_dataset)
    scribe('test_dataset', test_dataset_2)

In [12]:
wd1_file_path = '/home/e78368jw/Documents/MULE/packs/tests/data/one_channel_WD1_tmp.h5'

In [13]:
q = pd.read_hdf(wd1_file_path, 'RAW/event_info')
display(q)

       event_number   timestamp  samples  sampling_period  channels
0                 0       44253      130                2         1
1                 1      169253      130                2         1
2                 2      294255      130                2         1
3                 3      419255      130                2         1
4                 4      544255      130                2         1
...             ...         ...      ...              ...       ...
9997           9997  1249674263      130                2         1
9998           9998  1249799263      130                2         1
9999           9999  1249924265      130                2         1
10000         10000  1250049265      130                2         1
10001         10001  1250174265      130                2         1

[10002 rows x 5 columns]

In [19]:
scholar = reader(wd1_file_path, 'RAW', 'rwf')
q = [x for x in scholar]
print(q)

#with reader(wd1_file_path, 'RAW', 'rwf') as scholar:
#    print(list(scholar))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [22]:
print(q[10])

(10, 0, [7710, 7692, 7713, 7702, 7709, 7701, 7711, 7702, 7702, 7713, 7695, 7710, 7700, 7710, 7702, 7709, 7707, 7696, 7706, 7699, 7711, 7699, 7708, 7704, 7712, 7702, 7700, 7707, 7700, 7708, 7698, 7711, 7701, 7711, 7698, 7705, 7708, 7708, 7697, 7703, 7705, 7704, 7704, 7703, 7704, 7703, 7713, 7704, 7702, 7706, 7707, 7703, 7707, 7702, 7705, 7707, 7706, 7698, 7703, 7706, 7703, 7705, 7705, 7705, 7708, 7700, 7701, 7705, 7705, 7710, 7698, 7707, 7705, 7708, 7698, 7704, 7709, 7706, 7701, 7709, 7696, 7708, 7704, 7707, 7707, 7707, 7709, 7698, 7708, 7708, 7706, 7699, 7710, 7704, 7709, 7710, 7705, 7708, 7708, 7708, 7700, 7703, 7704, 7705, 7702, 7711, 7698, 7712, 7705, 7708, 7703, 7703, 7706, 7697, 7710, 7704, 7703, 7701, 7703, 7711, 7699, 7708, 7706, 7705, 7705, 7707, 7704, 7704, 7702, 7708])

In [2]:
display(pd.read_hdf('test_file.h5', 'test_group/test_dataset'))

   int  float  bool  bigfloat
0    0    1.0     0     25.23
1    5    4.0     1     99.99
2    0    1.0     0     25.23
3    5    4.0     1     99.99
4    0    1.0     0     25.23
5    5    4.0     1     99.99
6    0    1.0     0     25.23
7    5    4.0     1     99.99

In [10]:
x = [0,1,2,3,4,5,6,7]
print(x[2:])

[2, 3, 4, 5, 6, 7]

In [14]:
a = reader('test_file.h5', 'test_group', 'test_dataset')

try:
    while True:
        print(next(a))
except StopIteration:
    print("Donezo!")

(0, 1., False, 25.23)
(5, 4., True, 99.99)
(0, 1., False, 25.23)
(5, 4., True, 99.99)
(0, 1., False, 25.23)
(5, 4., True, 99.99)
(0, 1., False, 25.23)
(5, 4., True, 99.99)
Donezo!

In [21]:
q = pd.read_hdf('test_file.h5', 'test_group/test_dataset', iterator = True)
display(q)
for chunk in q:
    data = chunk.to_numpy()
    for row in data:
        display(row)

/tmp/ipykernel_72809/3405036771.py:3: IncompatibilityWarning:
where criteria is being ignored as this version [0.0.0] is too old (or
not-defined), read the file in and write it out to a new file to upgrade (with
the copy_to method)

  for chunk in q:

array([ 0.  ,  1.  ,  0.  , 25.23])

array([ 5.  ,  4.  ,  1.  , 99.99])

In [7]:
with reader('test_file.h5', 'test_group', 'test_dataset') as scholar:
    try:
        while True:    
            print(scholar)
    finally:
        print('we broke outta here')

if you read me many times, you suck!

ValueError: Invalid location identifier (invalid location identifier)

In [21]:
scroll = np.array(next(scholar))
print(scroll)

StopIteration:

In [13]:
print(scroll)
scroll.tolist()

(0, 1., False, 25.23)

(0, 1.0, False, 25.23)

In [38]:
test_dataset.tolist() == scroll.tolist()

True